# Generated by Django 5.2.9 on 2026-01-01 11:15

import django.core.validators
import technical_repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldocumentversion',
            name='pdf_file',
            field=models.FileField(max_length=300, upload_to=technical_repository.models.technical_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
