# Generated by Django 5.2.9 on 2026-01-03 20:55

import django.core.validators
import technical_repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_repository', '0002_alter_technicaldocumentversion_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaldocument',
            name='pdf_file',
            field=models.FileField(default='', max_length=300, upload_to=technical_repository.models.technical_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TechnicalDocumentVersion',
        ),
    ]
