# Generated by Django 5.2.9 on 2026-01-01 23:31

import technical_repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_repository', '0003_technicaldocument_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaldocument',
            name='cover_image',
            field=models.ImageField(blank=True, default='tech_archive/defaults/pdf_img.png', max_length=300, null=True, upload_to=technical_repository.models.technical_cover_upload_path),
        ),
    ]
