# Generated by Django 5.2.9 on 2025-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título'),
        ),
    ]
