# Generated by Django 5.2.9 on 2025-12-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0003_postcomment_postlike_postrating_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
