# Generated by Django 5.2.9 on 2025-12-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_background_image_group_description_and_more'),
        ('social_net', '0004_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.group', verbose_name='Grupo'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', 'created_at'], name='social_net__group_i_be0ff4_idx'),
        ),
    ]
