# Generated by Django 5.2.9 on 2025-12-30 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0005_post_group_post_social_net__group_i_be0ff4_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='social_net.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postagem ocultada',
                'verbose_name_plural': 'Postagens ocultadas',
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_hidden_per_user')],
            },
        ),
    ]
