# Generated by Django 5.2.9 on 2026-01-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0006_posthidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link relacionado'),
        ),
    ]
