# Generated by Django 5.2.9 on 2026-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0007_post_related_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opened_by_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='opened_by_third_party_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
