# Generated by Django 5.1.4 on 2024-12-20 13:18

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0002_alter_customusermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_picture',
            field=stdimage.models.StdImageField(blank=True, default='profile_pics/usercommonimg.jpg', force_min_size=False, null=True, upload_to='profile_pics/', variations={'thumbnail': (200, 200)}),
        ),
    ]
