# Generated by Django 5.1.4 on 2024-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0003_customusermodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='director',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Diretor do Instituto de Criminalística'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome de Exibição'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não informar')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='team',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Equipe de Perícias Criminalísticas'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Núcleo'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/usercommonimg.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
