# Generated by Django 5.1.4 on 2024-12-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0004_customusermodel_city_customusermodel_director_and_more'),
        ('postsapp', '0002_alter_postmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='hidden_posts',
            field=models.ManyToManyField(blank=True, related_name='hidden_by_users', to='postsapp.postmodel'),
        ),
    ]
