# Generated by Django 5.1.4 on 2024-12-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0006_customusermodel_dark_theme'),
        ('postsapp', '0002_alter_postmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='postsapp.postmodel'),
        ),
    ]
