# Generated by Django 5.1.4 on 2024-12-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0007_customusermodel_liked_posts'),
        ('postsapp', '0003_commentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='liked_comments',
            field=models.ManyToManyField(blank=True, related_name='commented_liked_by_users', to='postsapp.commentsmodel'),
        ),
    ]
