# Generated by Django 5.2.9 on 2025-12-26 18:48

import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=groups.models.group_background_image_path, verbose_name='Imagem de fundo'),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='group',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=groups.models.group_profile_image_path, verbose_name='Imagem de perfil'),
        ),
    ]
