# Generated by Django 5.2.9 on 2026-01-05 19:15

import django.db.models.deletion
import report_maker.models.images
import report_maker.models.report_case
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Número do laudo')),
                ('protocol', models.CharField(blank=True, max_length=50, verbose_name='Protocolo')),
                ('objective', models.CharField(choices=[('INITIAL_EXAM', 'Exame inicial'), ('COMPLEMENTARY_EXAM', 'Exame complementar'), ('VEHICLE_EXAM', 'Exame em veículo automotor'), ('SIMULATED_RECONSTRUCTION', 'Reprodução simulada'), ('OTHER', 'Outro')], default='INITIAL_EXAM', max_length=40, verbose_name='Objetivo')),
                ('requesting_authority', models.CharField(max_length=120, verbose_name='Autoridade requisitante')),
                ('police_report', models.CharField(blank=True, max_length=60, verbose_name='Boletim de ocorrência')),
                ('police_inquiry', models.CharField(blank=True, max_length=60, verbose_name='Inquérito policial')),
                ('police_station', models.CharField(blank=True, max_length=120, verbose_name='Distrito policial')),
                ('occurrence_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da ocorrência')),
                ('assignment_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da designação')),
                ('examination_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora do exame pericial')),
                ('photography_by', models.CharField(blank=True, max_length=120, verbose_name='Fotografia')),
                ('sketch_by', models.CharField(blank=True, max_length=120, verbose_name='Croqui')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusão')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Concluído')], db_index=True, default='OPEN', max_length=20, verbose_name='Status')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Bloqueado para edição')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=report_maker.models.report_case.report_pdf_upload_path, verbose_name='PDF do laudo')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cases', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Laudo',
                'verbose_name_plural': 'Laudos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='Objeto')),
                ('image', models.ImageField(upload_to=report_maker.models.images.object_image_upload_path, verbose_name='Imagem')),
                ('caption', models.CharField(max_length=240, verbose_name='Legenda')),
                ('index', models.PositiveIntegerField(verbose_name='Índice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('report_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_images', to='report_maker.reportcase', verbose_name='Laudo')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='GenericExamObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('methodology', models.TextField(blank=True, verbose_name='Metodologia')),
                ('examination', models.TextField(blank=True, verbose_name='Exame')),
                ('results', models.TextField(blank=True, verbose_name='Resultados')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('report_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='report_maker.reportcase', verbose_name='Laudo')),
            ],
            options={
                'verbose_name': 'Objeto genérico',
                'verbose_name_plural': 'Objetos genéricos',
            },
        ),
        migrations.AddIndex(
            model_name='reportcase',
            index=models.Index(fields=['status', 'updated_at'], name='report_make_status_ac6cbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectimage',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'index'), name='unique_image_index_per_object'),
        ),
    ]
