# Generated by Django X.Y on YYYY-MM-DD HH:MM
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_maker", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- gera UUIDs no banco
                    CREATE EXTENSION IF NOT EXISTS "pgcrypto";

                    -- 1) cria nova coluna uuid com default
                    ALTER TABLE report_maker_genericexamobject
                    ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();

                    -- 2) preenche (caso existam linhas antigas)
                    UPDATE report_maker_genericexamobject
                    SET id_uuid = gen_random_uuid()
                    WHERE id_uuid IS NULL;

                    -- 3) remove PK antiga e coluna antiga
                    ALTER TABLE report_maker_genericexamobject
                    DROP CONSTRAINT IF EXISTS report_maker_genericexamobject_pkey;

                    ALTER TABLE report_maker_genericexamobject
                    DROP COLUMN IF EXISTS id;

                    -- 4) renomeia e recria PK
                    ALTER TABLE report_maker_genericexamobject
                    RENAME COLUMN id_uuid TO id;

                    ALTER TABLE report_maker_genericexamobject
                    ADD PRIMARY KEY (id);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="genericexamobject",
                    name="id",
                    field=models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                # Se o Django tinha gerado AlterField do report_case também,
                # mantenha aqui (ou deixe o seu model mandar).
                migrations.AlterField(
                    model_name="genericexamobject",
                    name="report_case",
                    field=models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="exam_objects",
                        to="report_maker.reportcase",
                        verbose_name="Laudo",
                    ),
                ),
            ],
        ),
    ]
