# Generated by Django 5.2.9 on 2026-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0002_alter_genericexamobject_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectimage',
            options={'ordering': ['index', 'id'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.RemoveField(
            model_name='objectimage',
            name='report_case',
        ),
        migrations.AlterField(
            model_name='objectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=240, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='objectimage',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Índice'),
        ),
    ]
