# Generated by Django 5.2.9 on 2026-01-08 19:56

import report_maker.models.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0003_alter_objectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=report_maker.models.images.object_image_upload_path, verbose_name='Imagem'),
        ),
    ]
