# Generated by Django 5.2.9 on 2026-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0004_alter_objectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectimage',
            name='original_height',
            field=models.PositiveIntegerField(default=0, help_text='Altura da imagem original em pixels.', verbose_name='Altura original (px)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectimage',
            name='original_width',
            field=models.PositiveIntegerField(default=0, help_text='Largura da imagem original em pixels.', verbose_name='Largura original (px)'),
            preserve_default=False,
        ),
    ]
