# Generated by Django 5.2.9 on 2026-01-12 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_remove_nucleo_cidade_remove_nucleo_institution_and_more'),
        ('report_maker', '0005_objectimage_original_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_cases', to='institutions.institution', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='institution_acronym_snapshot',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Sigla da instituição (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='institution_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da instituição (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='nucleus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_cases', to='institutions.nucleus', verbose_name='Núcleo'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='nucleus_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do núcleo (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='organization_frozen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Organização congelada em'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_cases', to='institutions.team', verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='team_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da equipe (snapshot)'),
        ),
        migrations.AddIndex(
            model_name='reportcase',
            index=models.Index(fields=['organization_frozen_at', 'updated_at'], name='report_make_organiz_e04ccd_idx'),
        ),
    ]
