# Generated by Django 5.2.9 on 2026-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0006_reportcase_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='criminal_typification',
            field=models.CharField(blank=True, help_text='Ex.: furto, roubo, homicídio, latrocínio', max_length=80, verbose_name='Tipificação penal'),
        ),
    ]
