# Generated by Django 5.2.9 on 2026-01-15 00:22

import report_maker.models.report_case
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0007_reportcase_criminal_typification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='emblem_primary_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to=report_maker.models.report_case.report_header_emblem_upload_path, verbose_name='Emblema primário (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='emblem_secondary_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to=report_maker.models.report_case.report_header_emblem_upload_path, verbose_name='Emblema secundário (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='honoree_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nome do homenageado (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='honoree_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Título do homenageado (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='institution_kind_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Kind institucional (snapshot)'),
        ),
    ]
