# Generated by Django 5.2.9 on 2026-01-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0008_reportcase_emblem_primary_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcase',
            name='conclusion',
        ),
    ]
