# Generated by Django 5.2.9 on 2026-01-21 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0009_remove_reportcase_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTextBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement', models.CharField(choices=[('PREAMBLE', 'Preâmbulo (substituto do sistema)'), ('AFTER_PREAMBLE', 'Após preâmbulo'), ('BEFORE_OBJECTS', 'Antes dos objetos de exame (geral)'), ('LOCATIONS_INTRO', 'Locais – texto introdutório'), ('VEHICLES_INTRO', 'Objetos genéricos – texto introdutório'), ('AFTER_OBJECTS', 'Após os objetos de exame'), ('FINAL_CONSIDERATIONS', 'Considerações finais'), ('CONCLUSION', 'Conclusão')], db_index=True, default='AFTER_PREAMBLE', max_length=40, verbose_name='Posição no laudo')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Texto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('report_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='report_maker.reportcase', verbose_name='Laudo')),
            ],
            options={
                'verbose_name': 'Texto do laudo',
                'verbose_name_plural': 'Textos do laudo',
                'ordering': ['placement', 'order', 'created_at'],
                'indexes': [models.Index(fields=['report_case', 'placement', 'order'], name='report_make_report__0f334a_idx')],
            },
        ),
    ]
