# Generated by Django 5.2.9 on 2026-01-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0010_reporttextblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericexamobject',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='results',
        ),
        migrations.AlterField(
            model_name='genericexamobject',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição geral e identificadora do objeto examinado.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='genericexamobject',
            name='title',
            field=models.CharField(blank=True, help_text='Identificação sucinta do objeto no laudo.', max_length=160, verbose_name='Título do objeto'),
        ),
    ]
