# Generated by Django 5.2.9 on 2026-01-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0011_remove_genericexamobject_examination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericexamobject',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem de apresentação do objeto no laudo.', verbose_name='Ordem'),
        ),
    ]
