# Generated by Django 5.2.9 on 2026-01-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0012_genericexamobject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericexamobject',
            name='order',
            field=models.PositiveIntegerField(editable=False, help_text='Ordem de exibição do objeto dentro do laudo.', verbose_name='Ordem'),
        ),
    ]
