# Generated by Django 5.2.9 on 2026-01-23 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0013_alter_genericexamobject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericexamobject',
            name='report_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', related_query_name='%(class)s_object', to='report_maker.reportcase'),
        ),
        migrations.CreateModel(
            name='PublicRoadExamObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(editable=False, help_text='Ordem de exibição do objeto dentro do laudo.', verbose_name='Ordem')),
                ('title', models.CharField(blank=True, help_text='Identificação sucinta do objeto no laudo.', max_length=160, verbose_name='Título do objeto')),
                ('description', models.TextField(blank=True, help_text='Descrição geral e identificadora do objeto examinado.', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('observed_elements', models.TextField(blank=True, verbose_name='Resultados')),
                ('weather_conditions', models.TextField(blank=True, verbose_name='Condições climáticas')),
                ('road_conditions', models.TextField(blank=True, verbose_name='Condições da via')),
                ('traffic_signage', models.TextField(blank=True, verbose_name='Sinalização viária')),
                ('report_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', related_query_name='%(class)s_object', to='report_maker.reportcase')),
            ],
            options={
                'verbose_name': 'Exame de Via Pública',
                'verbose_name_plural': 'Exames de Via Pública',
            },
        ),
    ]
