# Generated by Django 5.2.9 on 2026-01-23 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0014_alter_genericexamobject_report_case_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericexamobject',
            options={'ordering': ('order',), 'verbose_name': 'Objeto genérico', 'verbose_name_plural': 'Objetos genéricos'},
        ),
        migrations.AlterModelOptions(
            name='publicroadexamobject',
            options={'ordering': ('order',), 'verbose_name': 'Exame de Via Pública', 'verbose_name_plural': 'Exames de Via Pública'},
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='report_case',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='genericexamobject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='report_case',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publicroadexamobject',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='ExamObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(editable=False, help_text='Ordem de exibição do objeto dentro do laudo.', verbose_name='Ordem')),
                ('title', models.CharField(blank=True, help_text='Identificação sucinta do objeto no laudo.', max_length=160, verbose_name='Título do objeto')),
                ('description', models.TextField(blank=True, help_text='Descrição geral e identificadora do objeto examinado.', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('report_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_objects', related_query_name='exam_object', to='report_maker.reportcase')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='genericexamobject',
            name='examobject_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_maker.examobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicroadexamobject',
            name='examobject_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_maker.examobject'),
            preserve_default=False,
        ),
    ]
