# Generated by Django 5.2.9 on 2026-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0015_alter_genericexamobject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examobject',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Ordem de exibição do objeto dentro do laudo.', verbose_name='Ordem'),
        ),
        migrations.AddConstraint(
            model_name='examobject',
            constraint=models.UniqueConstraint(fields=('report_case', 'order'), name='uq_examobject_reportcase_order'),
        ),
    ]
