# Generated by Django 5.2.9 on 2026-01-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0016_alter_examobject_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examobject',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Ordem de exibição do objeto dentro do laudo.', null=True, verbose_name='Ordem'),
        ),
    ]
