# Generated by Django 5.2.9 on 2026-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('report_maker', '0017_alter_examobject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimage',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Índice'),
        ),
        migrations.AlterField(
            model_name='publicroadexamobject',
            name='observed_elements',
            field=models.TextField(blank=True, verbose_name='Elementos Observados'),
        ),
        migrations.AddIndex(
            model_name='objectimage',
            index=models.Index(fields=['content_type', 'object_id'], name='report_make_content_7ad6c8_idx'),
        ),
    ]
