# Generated by Django 5.2.9 on 2026-01-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0018_alter_objectimage_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttextblock',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'Texto do laudo', 'verbose_name_plural': 'Textos do laudo'},
        ),
        migrations.RemoveIndex(
            model_name='reporttextblock',
            name='report_make_report__0f334a_idx',
        ),
        migrations.RemoveField(
            model_name='reporttextblock',
            name='order',
        ),
        migrations.AddField(
            model_name='reporttextblock',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, help_text="Usado apenas em 'Texto comum do grupo de objetos'. Ex.: LOCATIONS, VEHICLES...", max_length=40, verbose_name='Chave do grupo'),
        ),
        migrations.AddField(
            model_name='reporttextblock',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Posição no laudo'),
        ),
        migrations.AlterField(
            model_name='reporttextblock',
            name='placement',
            field=models.CharField(choices=[('PREAMBLE', 'Preâmbulo'), ('SUMMARY', 'Resumo'), ('TOC', 'Sumário'), ('OBJECT_GROUP_INTRO', 'Texto comum do grupo de objetos'), ('OBSERVATIONS', 'Observações'), ('FINAL_CONSIDERATIONS', 'Considerações finais'), ('CONCLUSION', 'Conclusão')], db_index=True, max_length=40, verbose_name='Tipo do bloco'),
        ),
        migrations.AddIndex(
            model_name='reporttextblock',
            index=models.Index(fields=['report_case', 'position'], name='report_make_report__e9ddc7_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttextblock',
            index=models.Index(fields=['report_case', 'placement', 'group_key'], name='report_make_report__8b8bc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='reporttextblock',
            constraint=models.UniqueConstraint(condition=models.Q(('placement__in', ['PREAMBLE', 'SUMMARY', 'TOC', 'OBSERVATIONS', 'FINAL_CONSIDERATIONS', 'CONCLUSION'])), fields=('report_case', 'placement'), name='uq_report_textblock_singleton_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='reporttextblock',
            constraint=models.UniqueConstraint(condition=models.Q(('placement', 'OBJECT_GROUP_INTRO')), fields=('report_case', 'placement', 'group_key'), name='uq_report_textblock_group_intro_per_key'),
        ),
    ]
