# Generated by Django 5.2.9 on 2026-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0019_alter_reporttextblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examobject',
            name='group_key',
            field=models.CharField(choices=[('LOCATIONS', 'Locais'), ('VEHICLES', 'Veículos'), ('PARTS', 'Peças'), ('CADAVERS', 'Cadáveres'), ('OTHER', 'Outros')], db_index=True, default='OTHER', editable=False, help_text='Agrupamento lógico no laudo (Locais, Veículos, Peças, Cadáveres...).', max_length=24, verbose_name='Grupo'),
        ),
    ]
