# Generated by Django 5.2.9 on 2026-01-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0020_examobject_group_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examobject',
            name='group_key',
            field=models.CharField(blank=True, choices=[('LOCATIONS', 'Locais'), ('VEHICLES', 'Veículos'), ('PARTS', 'Peças'), ('CADAVERS', 'Cadáveres'), ('OTHER', 'Outros')], db_index=True, editable=False, help_text='Agrupamento lógico no laudo (Locais, Veículos, Peças, Cadáveres...). Vazio = sem grupo.', max_length=24, null=True, verbose_name='Grupo'),
        ),
    ]
