# Generated by Django 5.2.9 on 2026-01-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0021_alter_examobject_group_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttextblock',
            name='title',
        ),
        migrations.AlterField(
            model_name='reporttextblock',
            name='body',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='reporttextblock',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Chave do grupo'),
        ),
    ]
