# Generated by Django 5.2.9 on 2026-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0022_remove_reporttextblock_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttextblock',
            name='group_key',
            field=models.CharField(db_index=True, default='__GLOBAL__', max_length=40, verbose_name='Chave do grupo'),
        ),
    ]
