# Generated by Django 5.2.9 on 2026-01-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0023_alter_reporttextblock_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='objective_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Objetivo (descrição livre)'),
        ),
        migrations.AlterField(
            model_name='reportcase',
            name='objective',
            field=models.CharField(blank=True, choices=[('INITIAL_EXAM', 'Exame inicial'), ('COMPLEMENTARY_EXAM', 'Exame complementar'), ('VEHICLE_EXAM', 'Exame em veículo automotor'), ('SIMULATED_RECONSTRUCTION', 'Reprodução simulada'), ('OTHER', 'Outro')], default='', max_length=40, verbose_name='Objetivo (tipo)'),
        ),
    ]
