# Generated by Django 5.2.9 on 2026-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0024_reportcase_objective_text_alter_reportcase_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicroadexamobject',
            name='geo_location',
            field=models.CharField(blank=True, help_text='Cole coordenadas, link do Maps, plus code ou endereço (uma linha).', max_length=255, null=True, verbose_name='Localização geográfica (Google Maps)'),
        ),
    ]
