# Generated by Django 5.2.9 on 2026-02-04 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0025_publicroadexamobject_geo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspectionExamObject',
            fields=[
                ('examobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_maker.examobject')),
                ('methodology', models.TextField(blank=True, verbose_name='Metodologia')),
                ('observed_elements', models.TextField(blank=True, verbose_name='Elementos Observados')),
                ('methodology_kind', models.CharField(blank=True, choices=[('VISUAL_INSPECTION', 'Vistoria (inspeção visual)'), ('LUMINOL', 'Luminol (pesquisa de sangue latente)'), ('FORENSIC_LIGHTS', 'Busca por vestígios latentes com luzes forenses')], default='', help_text='Selecione o tipo principal de procedimento aplicado.', max_length=40, verbose_name='Metodologia (tipo)')),
                ('operational_tests', models.TextField(blank=True, help_text='Ex.: acionamentos, funcionamento de sistemas, verificações específicas.', verbose_name='Testes operacionais')),
                ('tire_conditions', models.TextField(blank=True, help_text='Ex.: estado geral, desgaste, calibragem (se aferida), avarias visíveis.', verbose_name='Condições dos pneus')),
                ('optional_notes', models.TextField(blank=True, help_text='Campo livre para consignações técnicas pontuais relacionadas ao exame.', verbose_name='Texto opcional')),
            ],
            options={
                'verbose_name': 'Vistoria de Veículo',
                'verbose_name_plural': 'Vistorias de Veículos',
                'ordering': ('order',),
            },
            bases=('report_maker.examobject', models.Model),
        ),
    ]
