# Generated by Django 5.2.9 on 2026-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0026_vehicleinspectionexamobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspectionexamobject',
            name='methodology_kind',
            field=models.CharField(blank=True, choices=[('Vistoria Veicular', 'Vistoria (inspeção visual)'), ('Sangue Latente', 'Luminol (pesquisa de sangue latente)'), ('FORENSIC_LIGHTS', 'Busca por vestígios latentes com luzes forenses')], default='', help_text='Selecione o tipo principal de procedimento aplicado.', max_length=40, verbose_name='Metodologia (tipo)'),
        ),
    ]
