# Generated by Django 5.2.9 on 2026-02-05 15:14

import django.db.models.deletion
import report_maker.utils.google_maps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0027_alter_vehicleinspectionexamobject_methodology_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericLocationExamObject',
            fields=[
                ('examobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_maker.examobject')),
                ('observed_elements', models.TextField(blank=True, verbose_name='Elementos Observados')),
                ('geo_location', models.CharField(blank=True, help_text='Cole coordenadas, link do Maps, plus code ou endereço (uma linha).', max_length=255, null=True, verbose_name='Localização geográfica (Google Maps)')),
            ],
            options={
                'verbose_name': 'Local (genérico)',
                'verbose_name_plural': 'Locais (genéricos)',
                'ordering': ('order',),
            },
            bases=(report_maker.utils.google_maps.GoogleMapsLocationMixin, 'report_maker.examobject', models.Model),
        ),
    ]
