# Generated by Django 5.2.9 on 2026-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0028_genericlocationexamobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericlocationexamobject',
            name='service_context',
            field=models.CharField(blank=True, help_text='Informações sobre preservação do local, presença da autoridade requisitante, isolamento, intervenções prévias etc.', max_length=255, null=True, verbose_name='Contexto do atendimento'),
        ),
    ]
