# Generated by Django 5.2.9 on 2026-02-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0029_genericlocationexamobject_service_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericlocationexamobject',
            name='service_context',
            field=models.TextField(blank=True, default='contexto de atendimento', help_text='Informações sobre preservação do local, presença da autoridade requisitante, isolamento, intervenções prévias etc.', verbose_name='Contexto do atendimento'),
            preserve_default=False,
        ),
    ]
