# Generated by Django 5.2.9 on 2026-02-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0030_alter_genericlocationexamobject_service_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicroadexamobject',
            name='service_context',
            field=models.TextField(blank=True, help_text='Informações sobre preservação do local, presença da autoridade requisitante, isolamento, intervenções prévias etc.', verbose_name='Contexto do atendimento'),
        ),
    ]
