# Generated by Django 5.2.9 on 2026-02-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0031_publicroadexamobject_service_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcase',
            name='pdf_file',
        ),
    ]
