# Generated by Django 5.2.9 on 2026-02-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0032_remove_reportcase_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadaverExamObject',
            fields=[
                ('examobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_maker.examobject')),
                ('name', models.CharField(blank=True, help_text='Identificação nominal quando disponível (pode ser ignorado se desconhecido).', max_length=160, verbose_name='Nome')),
                ('perinecroscopic_exam', models.TextField(blank=True, default='Foi realizado exame perinecroscópico do cadáver no local, com observação externa da posição, indumentária, rigidez cadavérica, hipóstases, eventuais lesões aparentes e demais características visíveis, sem a realização de procedimentos invasivos.', help_text='Procedimentos adotados no exame externo do cadáver no local.', verbose_name='Exame perinecroscópico')),
                ('hypostasis', models.TextField(blank=True, help_text='Distribuição, coloração e fixidez, quando observadas.', verbose_name='Hipóstases')),
                ('injuries', models.TextField(blank=True, help_text='Lesões externas observadas (localização e características objetivas).', verbose_name='Lesões')),
                ('rigor', models.TextField(blank=True, help_text='Presença e grau/instalação, quando observada.', verbose_name='Rigidez cadavérica')),
                ('clothing', models.TextField(blank=True, help_text='Vestuário e condições/posição das peças.', verbose_name='Indumentária')),
                ('tattoos', models.TextField(blank=True, help_text='Descrição e localização das tatuagens, quando existentes.', verbose_name='Tatuagens')),
                ('body_adornments', models.TextField(blank=True, help_text='Ex.: brincos, piercings, anéis, correntes e similares, quando presentes.', verbose_name='Adornos fixados ao corpo')),
                ('observations', models.TextField(blank=True, help_text='Consignações técnicas complementares.', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Exame de Cadáver',
                'verbose_name_plural': 'Exames de Cadáver',
                'ordering': ('order',),
            },
            bases=('report_maker.examobject',),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionexamobject',
            name='optional_notes',
            field=models.TextField(blank=True, help_text='Campo livre para consignações técnicas pontuais relacionadas ao exame.', verbose_name='Observações'),
        ),
    ]
