# Generated by Django 5.2.9 on 2026-02-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0033_cadaverexamobject_and_more'),
    ]

    operations = [
    ]
