# Generated by Django 5.2.9 on 2026-02-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0034_add_textblock_historic_placement'),
    ]

    operations = [
    ]
