# Generated by Django 5.2.9 on 2026-02-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0035_add_textblock_historic_placement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reporttextblock',
            name='uq_report_textblock_singleton_per_placement',
        ),
        migrations.AlterField(
            model_name='reportcase',
            name='criminal_typification',
            field=models.CharField(blank=True, help_text='Ex.: furto, roubo, homicídio, latrocínio', max_length=80, verbose_name='Tipificação penal / Ocorrência'),
        ),
        migrations.AlterField(
            model_name='reporttextblock',
            name='placement',
            field=models.CharField(choices=[('PREAMBLE', 'Preâmbulo'), ('SUMMARY', 'Resumo'), ('TOC', 'Sumário'), ('HISTORIC', 'Histórico'), ('OBJECT_GROUP_INTRO', 'Texto comum do grupo de objetos'), ('OBSERVATIONS', 'Observações'), ('FINAL_CONSIDERATIONS', 'Considerações finais'), ('CONCLUSION', 'Conclusão')], db_index=True, max_length=40, verbose_name='Tipo do bloco'),
        ),
        migrations.AddConstraint(
            model_name='reporttextblock',
            constraint=models.UniqueConstraint(condition=models.Q(('placement__in', ['PREAMBLE', 'SUMMARY', 'TOC', 'HISTORIC', 'OBSERVATIONS', 'FINAL_CONSIDERATIONS', 'CONCLUSION'])), fields=('report_case', 'placement'), name='uq_report_textblock_singleton_per_placement'),
        ),
    ]
