# Generated by Django 5.2.9 on 2026-02-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0036_remove_reporttextblock_uq_report_textblock_singleton_per_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='city_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da Cidade (snapshot)'),
        ),
    ]
