# Generated by Django 5.2.9 on 2026-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_maker', '0037_reportcase_city_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='director_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do diretor (snapshot)'),
        ),
        migrations.AddField(
            model_name='reportcase',
            name='director_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cargo/Título do diretor (snapshot)'),
        ),
    ]
