# Generated by Django 5.1.4 on 2025-01-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0003_commentsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsmodel',
            options={'ordering': ['updated_at']},
        ),
    ]
