# Generated by Django 5.2.9 on 2025-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PERITO', 'Perito Criminal'), ('DELEGADO', 'Delegado de Polícia'), ('ESCRIVAO', 'Escrivão'), ('FOTOGRAFO', 'Fotógrafo Técnico Pericial')], help_text='Função do usuário no sistema.', max_length=20),
        ),
    ]
