# Generated by Django 5.2.9 on 2025-12-22 19:55

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('D', 'Recusada'), ('B', 'Bloqueada')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['from_user', 'status'], name='accounts_fr_from_us_8a2689_idx'), models.Index(fields=['to_user', 'status'], name='accounts_fr_to_user_c999b2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='no_self_friendship'), models.UniqueConstraint(django.db.models.functions.comparison.Least('from_user_id', 'to_user_id'), django.db.models.functions.comparison.Greatest('from_user_id', 'to_user_id'), name='uniq_friendship_undirected_pair')],
            },
        ),
    ]
