# Generated by Django 5.2.9 on 2025-12-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
