# Generated by Django 5.2.9 on 2025-12-29 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguir usuário',
                'verbose_name_plural': 'Seguidores e seguidos',
                'db_table': 'accounts_user_follow',
                'indexes': [models.Index(fields=['follower', 'is_active'], name='accounts_us_followe_809ffe_idx'), models.Index(fields=['following', 'is_active'], name='accounts_us_followi_2b93b6_idx'), models.Index(fields=['created_at'], name='accounts_us_created_8aa765_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='uniq_user_follow_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='chk_no_self_follow')],
            },
        ),
    ]
