# Generated by Django 5.2.9 on 2026-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit_reports',
            field=models.BooleanField(db_index=True, default=False, help_text='Habilita o usuário a criar/editar laudos (exige vínculo institucional ativo).'),
        ),
    ]
