# Generated by Django 5.2.9 on 2026-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_can_edit_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_signature_name',
            field=models.CharField(blank=True, help_text='Nome exibido nos Laudos. Ex: Dr. Marcos Capristo', max_length=200),
        ),
    ]
