# Generated by Django 5.2.9 on 2026-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_report_signature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_home',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('posts', 'Postagens')], default='dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro'), ('system', 'Sistema')], default='dark', max_length=10),
        ),
    ]
