# Generated by Django 5.2.9 on 2026-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_default_home_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_home',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('posts', 'Postagens'), ('groups', 'Grupos'), ('technical', 'Arquivo técnico'), ('reports', 'Laudos'), ('zen', 'Zen do Laudo')], default='dashboard', max_length=20),
        ),
    ]
