# Generated by Django 5.2.9 on 2026-02-06 03:25

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_default_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_reports',
            field=models.BooleanField(db_index=True, default=False, help_text='Habilita o usuário a criar novos laudos (exige vínculo institucional ativo).'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_reports_until',
            field=models.DateField(blank=True, db_index=True, default=accounts.models.default_can_create_reports_until, help_text='Data limite para criação de laudos. Se vazio (NULL), a criação permanece habilitada sem expiração (desde que can_create_reports=True). Padrão: 90 dias a partir da data de criação do registro.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo do usuário (faixa superior).', null=True, upload_to=accounts.models.user_background_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_edit_reports',
            field=models.BooleanField(db_index=True, default=False, help_text='Habilita o usuário a editar laudos já existentes (exige vínculo institucional ativo).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_home',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('posts', 'Postagens'), ('groups', 'Grupos'), ('technical', 'Arquivo técnico'), ('reports', 'Laudos'), ('zen', 'Zen do Laudo')], default='dashboard', help_text='Página inicial padrão ao entrar no sistema.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nome exibido na interface (fallback para username se vazio).', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único (UUID) do usuário.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagem de perfil do usuário.', null=True, upload_to=accounts.models.user_profile_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='report_signature_name',
            field=models.CharField(blank=True, help_text='Nome exibido no bloco de assinatura dos laudos (ex.: Dr. Marcos Capristo).', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro'), ('system', 'Sistema')], default='dark', help_text='Tema de interface preferido.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Data/hora de criação do vínculo (follow).'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='follower',
            field=models.ForeignKey(help_text='Usuário que segue.', on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='following',
            field=models.ForeignKey(help_text='Usuário seguido.', on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o vínculo está ativo.'),
        ),
    ]
