# Generated by Django 5.2.9 on 2026-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_can_create_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closing_phrase',
            field=models.TextField(blank=True, default='Nada mais havendo a consignar, encerra-se o presente laudo.', verbose_name='Frase de Fechamento'),
        ),
    ]
