# Generated by Django 5.2.9 on 2026-02-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_closing_phrase'),
        ('institutions', '0007_team_unique_team_name_per_nucleus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='institutions.team', verbose_name='Equipe'),
        ),
    ]
