# Generated by Django 5.2.9 on 2026-01-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('SPTC_SP', 'SPTC (SP)'), ('POLICIA_CIENTIFICA', 'Polícia Científica'), ('POLICIA_CIVIL', 'Polícia Civil'), ('OUTRA', 'Outra')], default='OUTRA', max_length=40)),
                ('diretor_nome', models.CharField(blank=True, default='', max_length=255)),
                ('diretor_cargo', models.CharField(blank=True, default='', max_length=255)),
                ('brasao_1', models.ImageField(blank=True, null=True, upload_to='institutions/brasoes/')),
                ('brasao_2', models.ImageField(blank=True, null=True, upload_to='institutions/brasoes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(default='SP', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Cidade da Instituição',
                'verbose_name_plural': 'Cidades da Instituição',
                'ordering': ['institution__sigla', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nucleos', to='institutions.institutioncity')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nucleos', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
                'ordering': ['institution__sigla', 'order', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='institutions.nucleo')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nucleo__institution__sigla', 'nucleo__order', 'order', 'nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='institutioncity',
            constraint=models.UniqueConstraint(fields=('institution', 'name', 'state'), name='unique_city_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='nucleo',
            constraint=models.UniqueConstraint(fields=('institution', 'nome'), name='unique_nucleo_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='equipe',
            constraint=models.UniqueConstraint(fields=('nucleo', 'nome'), name='unique_equipe_name_per_nucleo'),
        ),
    ]
