# Generated by Django 5.2.9 on 2026-01-11 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='institutions.federationunit')),
            ],
            options={
                'ordering': ['uf__code', 'name'],
                'unique_together': {('uf', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ForensicAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('superintendent_name', models.CharField(blank=True, max_length=120)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='institutions.institution')),
            ],
            options={
                'ordering': ['institution__uf__code', 'name', 'city'],
                'unique_together': {('institution', 'name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_units', to='institutions.forensicagency')),
            ],
            options={
                'ordering': ['agency__name', 'name'],
                'unique_together': {('agency', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_display_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_profile', to=settings.AUTH_USER_MODEL)),
                ('work_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.workunit')),
            ],
        ),
    ]
