# Generated by Django 5.2.9 on 2026-01-12 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nucleo',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='nucleo',
            name='institution',
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['acronym'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='institutioncity',
            options={'ordering': ['institution__acronym', 'order', 'name'], 'verbose_name': 'Institution City', 'verbose_name_plural': 'Institution Cities'},
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='sigla',
            new_name='acronym',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='diretor_nome',
            new_name='director_name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='diretor_cargo',
            new_name='director_title',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='brasao_1',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='brasao_2',
        ),
        migrations.AddField(
            model_name='institution',
            name='emblem_primary',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/emblems/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='emblem_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/emblems/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='kind',
            field=models.CharField(choices=[('SPTC_SP', 'SPTC (SP)'), ('SCIENTIFIC_POLICE', 'Scientific Police'), ('CIVIL_POLICE', 'Civil Police'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.CreateModel(
            name='Nucleus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nuclei', to='institutions.institutioncity')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuclei', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Nucleus',
                'verbose_name_plural': 'Nuclei',
                'ordering': ['institution__acronym', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('nucleus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='institutions.nucleus')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['nucleus__institution__acronym', 'nucleus__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserInstitutionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_primary', models.BooleanField(default=True, help_text="Defines whether this is the user's primary institution for the period.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_assignments', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Institution Assignment',
                'verbose_name_plural': 'User Institution Assignments',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_primary', models.BooleanField(default=True, help_text="Defines whether this is the user's primary team for the period.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_assignments', to='institutions.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Team Assignment',
                'verbose_name_plural': 'User Team Assignments',
                'ordering': ['-start_at'],
            },
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
        migrations.DeleteModel(
            name='Nucleo',
        ),
        migrations.AddConstraint(
            model_name='nucleus',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_nucleus_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('nucleus', 'name'), name='unique_team_name_per_nucleus'),
        ),
        migrations.AddIndex(
            model_name='userinstitutionassignment',
            index=models.Index(fields=['user', 'end_at'], name='institution_user_id_aaef51_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinstitutionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('user',), name='unique_active_institution_per_user'),
        ),
        migrations.AddIndex(
            model_name='userteamassignment',
            index=models.Index(fields=['user', 'end_at'], name='institution_user_id_8d3e7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userteamassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('user',), name='unique_active_team_per_user'),
        ),
    ]
