# Generated by Django 5.2.9 on 2026-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_remove_nucleo_cidade_remove_nucleo_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='honoree',
            field=models.CharField(blank=True, help_text='Nome do patrono ou homenageado institucional', max_length=200),
        ),
    ]
