# Generated by Django 5.2.9 on 2026-01-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_honoree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='honoree',
        ),
        migrations.AddField(
            model_name='institution',
            name='honoree_name',
            field=models.CharField(blank=True, help_text='Nome do patrono ou homenageado institucional', max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='honoree_title',
            field=models.CharField(blank=True, help_text='Título honorífico (ex.: Perito Criminal Dr.)', max_length=255),
        ),
    ]
