# Generated by Django 5.2.9 on 2026-01-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_remove_institution_honoree_institution_honoree_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='kind',
            field=models.CharField(choices=[('SCIENTIFIC_POLICE', 'Polícia Técnico-Científica'), ('CIVIL_POLICE', 'Polícia Civil'), ('MEDICAL_LEGAL', 'Instituto Médico-Legal'), ('CRIMINALISTICS', 'Instituto de Criminalística'), ('OTHER', 'Outro')], default='OTHER', max_length=40),
        ),
    ]
