# Generated by Django 5.2.9 on 2026-02-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_institution_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_name_per_nucleus',
        ),
        migrations.AddField(
            model_name='team',
            name='is_nucleus_team',
            field=models.BooleanField(default=False, help_text='Indica que esta equipe representa o próprio núcleo.'),
        ),
    ]
