# Generated by Django 5.2.9 on 2026-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_remove_team_unique_team_name_per_nucleus_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('nucleus', 'name'), name='unique_team_name_per_nucleus'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_nucleus_team', True)), fields=('nucleus',), name='unique_nucleus_team_per_nucleus'),
        ),
    ]
