# Generated by Django 5.1.4 on 2025-01-20 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_display_name', models.CharField(default='', max_length=200, verbose_name='Perito')),
                ('institute_director', models.CharField(default='', max_length=200, verbose_name='Diretor do Instituto')),
                ('institute_unit', models.CharField(default='', max_length=200, verbose_name='Núcleo do Instituto')),
                ('forensic_team_base', models.CharField(default='', max_length=200, verbose_name='Base da Equipe de Perícias')),
                ('report_number', models.CharField(default='', max_length=100, null=True, verbose_name='Número do Laudo')),
                ('protocol_number', models.CharField(default='', max_length=200, null=True, verbose_name='Número do Protocolo')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('designation_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Designação')),
                ('service_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Atendimento')),
                ('service_time', models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Atendimento')),
                ('photographer', models.CharField(default='', max_length=200, verbose_name='Fotografia')),
                ('considerations', models.TextField(blank=True, default='', verbose_name='Considerações')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='Conclusão')),
                ('police_report_number', models.CharField(default='', max_length=200, null=True, verbose_name='Número do Boletim de Ocorrência')),
                ('police_station', models.CharField(default='', max_length=200, null=True, verbose_name='Distrito Policial')),
                ('occurrence_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da Ocorrência')),
                ('occurrence_time', models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Atendimento')),
                ('city', models.CharField(default='Limeira', max_length=100, null=True, verbose_name='Cidade')),
                ('incident_nature', models.CharField(default='', max_length=300, null=True, verbose_name='Natureza da Ocorrência')),
                ('requesting_authority', models.CharField(default='', max_length=200, null=True, verbose_name='Autoridade Requisitante')),
                ('call_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Acionamento')),
                ('call_time', models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Acionamento')),
                ('examination_objective', models.CharField(default='', max_length=300, verbose_name='Objetivo do Exame')),
            ],
            options={
                'verbose_name': 'Relatório Pericial',
                'verbose_name_plural': 'Relatórios Periciais',
            },
        ),
    ]
