# Generated by Django 5.1 on 2024-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreportmodel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyreportmodel',
            name='legend',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='propertyreportmodel',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='propertyreportmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
