# Generated by Django 5.1 on 2024-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheftReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('report_number', models.CharField(default='indefinido', max_length=20, verbose_name='Número do Laudo')),
                ('city', models.CharField(default='Limeira', max_length=50, verbose_name='Cidade')),
                ('protocol_number', models.CharField(default='indefinido', max_length=20, verbose_name='Número do Protocolo')),
                ('occurring_number', models.CharField(default='indefinido', max_length=20, verbose_name='Número do Boletim')),
                ('designated_date', models.CharField(default='data indefinida!', max_length=20, verbose_name='Data de Designação')),
                ('exam_objective', models.CharField(default='indefinido', max_length=300, verbose_name='Objetivo do Exame')),
                ('occurrence_nature', models.CharField(default='indefinido', max_length=300, verbose_name='Natureza da Ocorrência')),
                ('police_station', models.CharField(default='indefinido', max_length=200, verbose_name='Distrito Policial')),
                ('requesting_authority', models.CharField(default='indefinido', max_length=200, verbose_name='Autoridade Requisitante')),
                ('activation_date', models.CharField(default='data indefinida!', max_length=20, verbose_name='Data do Acionamento')),
                ('activation_time', models.TimeField(blank=True, null=True, verbose_name='Hora do Acionamento')),
                ('service_date', models.CharField(default='data indefinida!', max_length=20, verbose_name='Data do Atendimento')),
                ('service_time', models.TimeField(verbose_name='Hora do Atendimento')),
                ('director', models.CharField(default='indefinido', max_length=200, verbose_name='Diretor')),
                ('nucleus', models.CharField(default='indefinido', max_length=200, verbose_name='Núcleo')),
                ('team', models.CharField(default='indefinido', max_length=200, verbose_name='Equipe de Perícias')),
                ('reporting_expert', models.CharField(default='indefinido', max_length=100, verbose_name='Perito Relator')),
                ('assistant_expert', models.CharField(blank=True, default='indefinido', max_length=100, null=True, verbose_name='Perito Assistente')),
                ('photographer', models.CharField(blank=True, default='indefinido', max_length=100, null=True, verbose_name='Fotógrafo')),
                ('draftsman', models.CharField(blank=True, default='indefinido', max_length=100, null=True, verbose_name='Desenhista')),
                ('considerations', models.TextField(blank=True, default='', verbose_name='Considerações')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='Conclusão')),
                ('burglary_scene', models.TextField(blank=True, default='', verbose_name='Descrição do Local')),
            ],
            options={
                'verbose_name': 'Local de Furto',
                'verbose_name_plural': 'Locais de Furto',
            },
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='city',
            field=models.CharField(default='Limeira', max_length=50, verbose_name='Cidade'),
        ),
    ]
