# Generated by Django 5.1 on 2024-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0002_theftreportmodel_alter_drugreport_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theftreportmodel',
            name='burglary_scene',
            field=models.JSONField(blank=True, default=list, verbose_name='Descrição do Local'),
        ),
    ]
