# Generated by Django 5.1 on 2024-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0002_userregistrationmodel_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='director',
            field=models.CharField(default='Dr. José Carlos de Freitas Garcia Caldas', help_text='Inclua do atual Diretor, incluindo Dr. ou Dra.', max_length=255),
        ),
    ]
