# Generated by Django 5.1.4 on 2025-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0003_reportmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Relatório Pericial', 'verbose_name_plural': 'Relatórios Periciais'},
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='has_authority_request',
            field=models.BooleanField(default=False, verbose_name='Requistado?'),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='has_police_report',
            field=models.BooleanField(default=False, verbose_name='Elaborado Boletim?'),
        ),
    ]
