# Generated by Django 5.1 on 2024-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0003_alter_theftreportmodel_burglary_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='theftreportmodel',
            name='preservation_context',
            field=models.TextField(blank=True, default='', verbose_name='Preservação'),
        ),
    ]
