# Generated by Django 5.1 on 2024-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0003_userregistrationmodel_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('report_number', models.CharField(default='indefinido', max_length=20, verbose_name='Número do Laudo')),
                ('protocol_number', models.CharField(default='indefinido', max_length=20, verbose_name='Número do Protocolo')),
                ('designated_date', models.DateField(verbose_name='Data de Designação')),
                ('exam_objective', models.CharField(default='indefinido', max_length=300, verbose_name='Objetivo do Exame')),
                ('occurrence_nature', models.CharField(default='indefinido', max_length=300, verbose_name='Natureza da Ocorrência')),
                ('police_station', models.CharField(default='indefinido', max_length=200, verbose_name='Distrito Policial')),
                ('requesting_authority', models.CharField(default='indefinido', max_length=200, verbose_name='Autoridade Requisitante')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Data do Acionamento')),
                ('activation_time', models.TimeField(blank=True, null=True, verbose_name='Hora do Acionamento')),
                ('service_date', models.DateField(verbose_name='Data do Atendimento')),
                ('service_time', models.TimeField(verbose_name='Hora do Atendimento')),
                ('director', models.CharField(default='indefinido', max_length=200, verbose_name='Diretor')),
                ('nucleus', models.CharField(default='indefinido', max_length=200, verbose_name='Núcleo')),
                ('team', models.CharField(default='indefinido', max_length=200, verbose_name='Equipe de Perícias')),
                ('reporting_expert', models.CharField(default='indefinido', max_length=100, verbose_name='Perito Relator')),
                ('assistant_expert', models.CharField(blank=True, default='indefinido', max_length=100, null=True, verbose_name='Perito Assistente')),
                ('photographer', models.CharField(blank=True, default='indefinido', max_length=100, null=True, verbose_name='Fotógrafo')),
                ('draftsman', models.CharField(blank=True, default='indefinido', max_length=100, null=True, verbose_name='Desenhista')),
                ('allSubstances', models.TextField(blank=True, default='[]')),
                ('materialReceivedObservations', models.TextField(blank=True, default='[]')),
                ('listOfEnvolvedPeople', models.TextField(blank=True, default='[]')),
                ('listItensLabels', models.TextField(blank=True, default='[]')),
                ('listOfPackagings', models.TextField(blank=True, default='[]')),
                ('listOfMorphology', models.TextField(blank=True, default='[]')),
                ('listOfGrossMass', models.TextField(blank=True, default='[]')),
                ('listOfLiquidMass', models.TextField(blank=True, default='[]')),
                ('listOfReturned', models.TextField(blank=True, default='[]')),
                ('listOfCounterProof', models.TextField(blank=True, default='[]')),
                ('listOfEntranceSeal', models.TextField(blank=True, default='[]')),
                ('listOfExitseal', models.TextField(blank=True, default='[]')),
                ('listOfpackagingAndMorphology', models.TextField(blank=True, default='[]')),
                ('listOfResultOfExams', models.TextField(blank=True, default='[]')),
            ],
            options={
                'verbose_name': 'Laudo de Drogas',
                'verbose_name_plural': 'Laudos de Drogas',
            },
        ),
    ]
