# Generated by Django 5.1 on 2024-10-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0004_theftreportmodel_preservation_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theftreportmodel',
            name='burglary_scene',
        ),
        migrations.AddField(
            model_name='theftreportmodel',
            name='localdescription',
            field=models.JSONField(blank=True, default=list, verbose_name='Imagem Base 64'),
        ),
        migrations.AddField(
            model_name='theftreportmodel',
            name='locallegend',
            field=models.JSONField(blank=True, default=list, verbose_name='Legenda da Imagem'),
        ),
        migrations.AddField(
            model_name='theftreportmodel',
            name='localsubtitle',
            field=models.JSONField(blank=True, default=list, verbose_name='Subtítulo'),
        ),
    ]
