# Generated by Django 5.1 on 2024-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0004_drugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugreport',
            name='occurring_number',
            field=models.CharField(default='indefinido', max_length=20, verbose_name='Número do Laudo'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='allSubstances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listItensLabels',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfCounterProof',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfEntranceSeal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfEnvolvedPeople',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfExitseal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfGrossMass',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfLiquidMass',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfMorphology',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfPackagings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfResultOfExams',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfReturned',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfpackagingAndMorphology',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='materialReceivedObservations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
