# Generated by Django 5.1.4 on 2025-01-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0004_alter_reportmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preservation_team', models.CharField(max_length=255, verbose_name='Equipe de Preservação')),
                ('officer_in_charge', models.CharField(max_length=255, verbose_name='Encarregado')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viatura')),
                ('preservation_conditions', models.TextField(verbose_name='Condições de Preservação')),
                ('police_authority_present', models.BooleanField(default=False, verbose_name='Autoridade Policial Presente')),
                ('investigation_team_present', models.BooleanField(default=False, verbose_name='Equipe de Investigação Presente')),
                ('general_context', models.TextField(verbose_name='Contexto Geral')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservations', to='myreportapp.reportmodel', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Preservação',
                'verbose_name_plural': 'Preservações',
            },
        ),
    ]
