# Generated by Django 5.1.4 on 2025-01-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0005_preservationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preservationmodel',
            old_name='vehicle',
            new_name='official_vehicle',
        ),
    ]
