# Generated by Django 5.1 on 2024-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0005_drugreport_occurring_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='occurring_number',
            field=models.CharField(default='indefinido', max_length=20, verbose_name='Número do Boletim'),
        ),
    ]
