# Generated by Django 5.1 on 2024-10-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0005_remove_theftreportmodel_burglary_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theftreportmodel',
            name='localimgbase64',
            field=models.JSONField(blank=True, default=list, verbose_name='Imagem Base 64'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='localdescription',
            field=models.JSONField(blank=True, default=list, verbose_name='Descrição'),
        ),
    ]
