# Generated by Django 5.1 on 2024-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0006_alter_drugreport_occurring_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugreport',
            name='listItensLabels',
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfCounterProof',
            field=models.TextField(blank=True, default='', verbose_name='Contraperícia'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfEntranceSeal',
            field=models.TextField(blank=True, default='', verbose_name='Lacre de entrada'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfEnvolvedPeople',
            field=models.TextField(blank=True, default='', verbose_name='Pessoas envolvidas'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfExitseal',
            field=models.TextField(blank=True, default='', verbose_name='Lacre de saída'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfGrossMass',
            field=models.TextField(blank=True, default='', verbose_name='Massa bruta'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfLiquidMass',
            field=models.TextField(blank=True, default='', verbose_name='Massa líquida'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfMorphology',
            field=models.TextField(blank=True, default='', verbose_name='Morfologia'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfPackagings',
            field=models.TextField(blank=True, default='', verbose_name='Embalagens'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfResultOfExams',
            field=models.TextField(blank=True, default='', verbose_name='Resultado do exame'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfReturned',
            field=models.TextField(blank=True, default='', verbose_name='Material retornado'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='listOfpackagingAndMorphology',
            field=models.TextField(blank=True, default='', verbose_name='Descrição do item'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='materialReceivedObservations',
            field=models.TextField(blank=True, default='', verbose_name='Todas as substâncias'),
        ),
    ]
