# Generated by Django 5.1 on 2024-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0006_theftreportmodel_localimgbase64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='activation_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data do Acionamento'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='designated_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data de Designação'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='service_date',
            field=models.CharField(max_length=20, verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='service_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do Atendimento'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='activation_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data do Acionamento'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='designated_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data de Designação'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='service_date',
            field=models.CharField(max_length=20, verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='service_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do Atendimento'),
        ),
    ]
