# Generated by Django 5.1 on 2024-09-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0007_remove_drugreport_listitenslabels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugreport',
            name='counterProofCaption',
            field=models.TextField(blank=True, default='', verbose_name='Legenda da contraperícia'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='counterProofImage',
            field=models.ImageField(blank=True, upload_to='counterproof_images/', verbose_name='Imagem da contraperícia'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='examImageCaptions',
            field=models.TextField(blank=True, default='', verbose_name='Legendas das imagens dos exames'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='examImages',
            field=models.ImageField(blank=True, upload_to='exam_images/', verbose_name='Imagens dos exames'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='listOfReturneds',
            field=models.TextField(blank=True, default='', verbose_name='Material retornado e contraperícia'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='materialImage',
            field=models.ImageField(blank=True, upload_to='material_images/', verbose_name='Fotografia do material'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='materialImageCaption',
            field=models.TextField(blank=True, default='', verbose_name='Legenda da fotografia do material'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='returnedItemsCaption',
            field=models.TextField(blank=True, default='', verbose_name='Legenda dos itens retornados'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='returnedItemsImage',
            field=models.ImageField(blank=True, upload_to='returned_items_images/', verbose_name='Imagem dos itens retornados'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='allSubstances',
            field=models.TextField(blank=True, default='', verbose_name='Substâncias examinadas'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='materialReceivedObservations',
            field=models.TextField(blank=True, default='', verbose_name='Observações sobre o material recebido'),
        ),
    ]
