# Generated by Django 5.1 on 2024-10-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0007_alter_drugreport_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='assistant_expert',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Perito Assistente'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='city',
            field=models.CharField(default='Limeira', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='designated_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data de Designação'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='director',
            field=models.CharField(default='', max_length=200, verbose_name='Diretor'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='draftsman',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Desenhista'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='exam_objective',
            field=models.CharField(default='', max_length=300, verbose_name='Objetivo do Exame'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='nucleus',
            field=models.CharField(default='', max_length=200, verbose_name='Núcleo'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='occurrence_nature',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Natureza da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='occurring_number',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Número do Boletim'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='photographer',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Fotógrafo'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='police_station',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Distrito Policial'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='protocol_number',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='report_number',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Número do Laudo'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='reporting_expert',
            field=models.CharField(default='', max_length=200, verbose_name='Perito Relator'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='requesting_authority',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Autoridade Requisitante'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='service_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='team',
            field=models.CharField(default='', max_length=200, verbose_name='Equipe de Perícias'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='assistant_expert',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Perito Assistente'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='city',
            field=models.CharField(default='Limeira', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='designated_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data de Designação'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='director',
            field=models.CharField(default='', max_length=200, verbose_name='Diretor'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='draftsman',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Desenhista'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='exam_objective',
            field=models.CharField(default='', max_length=300, verbose_name='Objetivo do Exame'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='nucleus',
            field=models.CharField(default='', max_length=200, verbose_name='Núcleo'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='occurrence_nature',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Natureza da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='occurring_number',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Número do Boletim'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='photographer',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Fotógrafo'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='police_station',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Distrito Policial'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='protocol_number',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='report_number',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Número do Laudo'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='reporting_expert',
            field=models.CharField(default='', max_length=200, verbose_name='Perito Relator'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='requesting_authority',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Autoridade Requisitante'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='service_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='theftreportmodel',
            name='team',
            field=models.CharField(default='', max_length=200, verbose_name='Equipe de Perícias'),
        ),
    ]
