# Generated by Django 5.1.4 on 2025-01-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0007_remove_preservationmodel_preservation_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='preservationmodel',
            name='section',
            field=models.CharField(default='Local - Preservação e Contexto do Atendimento', max_length=255, verbose_name='Seção'),
        ),
    ]
