# Generated by Django 5.1 on 2024-09-20 01:08

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0008_drugreport_counterproofcaption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='materialImage',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='drug_images/', variations={'large': (1417, None)}),
        ),
    ]
