# Generated by Django 5.1 on 2024-10-16 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0008_alter_drugreport_assistant_expert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default='1900-01-01', verbose_name='Data do Registro')),
                ('designation_date', models.DateField(default='1900-01-01', verbose_name='Data de Designação')),
                ('occurrence_date', models.DateField(default='1900-01-01', verbose_name='Data da Ocorrência')),
                ('activation_date', models.DateField(default='1900-01-01', verbose_name='Data do Acionamento')),
                ('activation_time', models.TimeField(blank=True, null=True, verbose_name='Hora do Acionamento')),
                ('service_date', models.DateField(default='1900-01-01', verbose_name='Data do Atendimento')),
                ('service_time', models.TimeField(blank=True, null=True, verbose_name='Hora do Atendimento')),
                ('report_number', models.CharField(default='', max_length=100, null=True, verbose_name='Número do Laudo')),
                ('city', models.CharField(default='Limeira', max_length=100, null=True, verbose_name='Cidade')),
                ('protocol_number', models.CharField(default='', max_length=200, null=True, verbose_name='Número do Protocolo')),
                ('police_report_number', models.CharField(default='', max_length=200, null=True, verbose_name='Número do Boletim de Ocorrência')),
                ('examination_objective', models.CharField(default='', max_length=300, verbose_name='Objetivo do Exame')),
                ('incident_nature', models.CharField(default='', max_length=300, null=True, verbose_name='Natureza da Ocorrência')),
                ('police_station', models.CharField(default='', max_length=200, null=True, verbose_name='Distrito Policial')),
                ('requesting_authority', models.CharField(default='', max_length=200, null=True, verbose_name='Autoridade Requisitante')),
                ('institute_director', models.CharField(default='', max_length=200, verbose_name='Diretor do Instituto')),
                ('institute_unit', models.CharField(default='', max_length=200, verbose_name='Núcleo do Instituto')),
                ('forensic_team_base', models.CharField(default='', max_length=200, verbose_name='Base da Equipe de Perícias')),
                ('expert_display_name', models.CharField(max_length=200, verbose_name='Nome do Perito Exibido no Relatório')),
                ('photographer', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Fotógrafo')),
                ('considerations', models.TextField(blank=True, default='', verbose_name='Considerações')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='Conclusão')),
                ('reporting_expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Perito Relator')),
            ],
            options={
                'verbose_name': 'Relatório Pericial',
                'verbose_name_plural': 'Relatórios Periciais',
            },
        ),
    ]
