# Generated by Django 5.1.4 on 2025-01-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0009_reportmodel_section_dataservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='section_request',
            field=models.CharField(default='Dados da Requisição', max_length=255, verbose_name='Dados da Requisição'),
        ),
    ]
