# Generated by Django 5.1 on 2024-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0009_alter_drugreport_materialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='materialImage',
            field=models.TextField(blank=True, default='', verbose_name='imagem do Material Recebido'),
        ),
    ]
