# Generated by Django 5.1 on 2024-10-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0009_headerreportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerreportmodel',
            name='occurrence_time',
            field=models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Atendimento'),
        ),
        migrations.AlterField(
            model_name='headerreportmodel',
            name='activation_time',
            field=models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Acionamento'),
        ),
        migrations.AlterField(
            model_name='headerreportmodel',
            name='service_time',
            field=models.TimeField(default='00:00:00', null=True, verbose_name='Hora do Atendimento'),
        ),
    ]
