# Generated by Django 5.1 on 2024-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0010_alter_drugreport_materialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='counterProofImage',
            field=models.TextField(blank=True, default='', verbose_name='imagem do material separado para contraperícia'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='examImageCaptions',
            field=models.TextField(blank=True, default='', verbose_name='Legendas da imagem do item examinado'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='examImages',
            field=models.TextField(blank=True, default='', verbose_name='imagem do item examinado'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='returnedItemsCaption',
            field=models.TextField(blank=True, default='', verbose_name='Legenda do Material retornado'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='returnedItemsImage',
            field=models.TextField(blank=True, default='', verbose_name='imagem do Material Retornado'),
        ),
    ]
