# Generated by Django 5.1.4 on 2025-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0010_reportmodel_section_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='user_preamble',
            field=models.TextField(blank=True, default='', verbose_name='Preâmbulo Confomre Usuário'),
        ),
    ]
