# Generated by Django 5.1 on 2024-10-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0011_alter_headerreportmodel_activation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenePreservationReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Preservação - Descrição')),
                ('reportForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_preservations', to='myreportapp.headerreportmodel', verbose_name='Relatório Principal')),
            ],
            options={
                'verbose_name': 'Preservação de Local',
            },
        ),
    ]
