# Generated by Django 5.1 on 2024-09-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0011_alter_drugreport_counterproofimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugreport',
            name='conclusion',
            field=models.TextField(blank=True, default='', verbose_name='Conclusão'),
        ),
        migrations.AddField(
            model_name='drugreport',
            name='considerations',
            field=models.TextField(blank=True, default='', verbose_name='Considerações'),
        ),
    ]
