# Generated by Django 5.1 on 2024-09-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0012_drugreport_conclusion_drugreport_considerations'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugreport',
            name='city',
            field=models.CharField(default='Limeira', max_length=50, verbose_name='Número do Laudo'),
        ),
    ]
