# Generated by Django 5.1 on 2024-10-22 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0012_scenepreservationreportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerreportmodel',
            name='activation_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Acionamento'),
        ),
        migrations.AlterField(
            model_name='headerreportmodel',
            name='designation_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Designação'),
        ),
        migrations.AlterField(
            model_name='headerreportmodel',
            name='occurrence_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='headerreportmodel',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Atendimento'),
        ),
        migrations.CreateModel(
            name='PropertyReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Imóvel - Descrição')),
                ('reportForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='myreportapp.headerreportmodel', verbose_name='Relatório Principal')),
            ],
            options={
                'verbose_name': 'Imóvel',
            },
        ),
    ]
