# Generated by Django 5.1 on 2024-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreportapp', '0013_drugreport_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreport',
            name='activation_date',
            field=models.CharField(default='data indefinida!', max_length=20, verbose_name='Data do Acionamento'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='designated_date',
            field=models.CharField(default='data indefinida!', max_length=20, verbose_name='Data de Designação'),
        ),
        migrations.AlterField(
            model_name='drugreport',
            name='service_date',
            field=models.CharField(default='data indefinida!', max_length=20, verbose_name='Data do Atendimento'),
        ),
    ]
